# Generated by Django 2.2.4 on 2019-08-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
